<template>
  <TechnicalTerms title="Les mots et abbréviations à connaître">
  </TechnicalTerms>
  <SwiperComponent :slides="technicalSlides"></SwiperComponent>
</template>
  
  <script>
  // @ is an alias to /src
  import SwiperComponent from "@/components/SwiperComponent.vue";
  import TechnicalTerms from "@/components/TechnicalTerms.vue";
  
  export default {
    name: "TechnicalTermsView",
    components: {
        TechnicalTerms,
        SwiperComponent,
    },
    data() {
        return {
            technicalSlides: [
                { title: "C.T.A | A.T.C", description: "Contrôle du Traffic Aérien | Air Traffic Control", details: "Structure au sol permettant de gérer toute une partie du ciel, qui est lui-même découpé en quartiers. Celle-ci utilise des radars ainsi que des communications radios. Elle forme par l'intermédiaire des contrôleurs aériens, une source d'information précieuse aux pilotes concernant les conditions météorologiques et les approches d'atterrissage. Le cas échéant, elle peut préconiser des déroutes et guider les pilotes en cas d'incident en vol" },
                { title: "U.A.A | A.P.U", description: "Unité d'Alimentation Auxiliaire | Auxiliary Power Unit", details: "Permet à un avion de produire sa propre énergie pour alimenter ses systèmes. D'ordinaire, le moteur à réaction est situé dans la queue de l'avion. Il peut servir au démarrage de l'avion ainsi qu'à sa pressurisation. Il est à noté qu'il s'agit davantage d'une source auxiliaire."  },
                { title: "B.E.A", description: "Bureau d'Enquêtes et d'Analyses", creation:"Création : 1946", details: "Le Bureau d'Enquêtes et d'Analyse pour la sécurité de l'aviation civile est une entité française, fondée en 1946, en charge des incidents graves (sur son sol ou dans les eaux internationnales si l'aéronef est de conception Française) impliquant les aéronefs civils. Toutefois, son rôle n'est pas de déterminer un responsable, mais de mener une investigation scientifique pour déterminer les causes exactes de l'incident. Elle dépend du ministère chargé des transports."},
                { title: "A.C | C.A.T", description: "Aviation Commerciale | Commercial Air Transport", details: "L'aviation commerciale est un service particulier dédié au transport de passagers, de marchandises ou de courrier contre rémunération ou tout autre avantage."  },
                { title: "C.R.N.A.", description: "Centre en-Route de la Navigation Aérienne (Contrôle les aéronefs IFR)", details: "Structure permettant de focaliser l'attention et la sécurité sur tous les appareils en vol. Ainsi, 'En route' signifie ici 'qui n'est ni en phase de décollage ou d'atterrissage', mais bien déjà présent dans les airs. La surveillance se fait sur un secteur bien défini du ciel. NB: En France, il existe cinq structures de ce genre : 'Brest, Athis-Mons, Aix-en-Provence, Reims et Bordeaux'."  },
                { title: "C.C.S", description: "Centre de Coordination Sauvetage | Rescue Coordination Center", details: "Entité fragmentée en trois parties : 'Maritime, Aéronautique, Conjointes'. Créé en 2015, cet organisme est basé à Lyon. Il reçoit les notifications de détresse, accuse leur réception et les retransmet. Enquête sur les zones probables d'accident. Organise et coordonne les recherches. (Dans le cadre d'incidents aériens, il en a la seule charge). Enfin, il peut mobiliser des moyens interministériels et interarmées."  },
                { title: "C.I.V | F.I.C", description: "Centre d'Information de Vol | Flight Information Center (Informe les aéronefs en vol à vue | Visual Flight Rules)", details: "Le centre d'information de vol peut, à la demande du pilote, délivrer des informations nécessaires au bon déroulement du vol (Informations météo, messages compagnies). Etant donné que le vol à vue obéit à certaines règles strictes, c'est une manière de voler particulièrement dangereuse. Il se focalise sur un espace aérien peu ou non contrôlé."  },
                { title: "C.C.A", description: "Cabin Crew Attestation", details: "Nécessaire à tous les individus dont la vocation est de servir et protéger dans les cieux, il s'agit d'une license européenne sous l'égide du règlement 290/2012. En effet, elle est nécessaire pour obtenir un emploi comme hôtesse de l'air ou steward au sein d'une compagnie de l'union européenne."  },
                { title: "C.R.D", description: "Child Restraint Device", details: "AmSafe's Child Aviation Restraint System (CARES) est un système de sécurité pour les enfants mesurant au moins un mètre, et pesant entre 10 et 20 kilos. Il permet de sécuriser l'assise en condition de mouvement sur la piste, de décollage, de turbulence, ou n'importe quelle situation dans laquelle le pilote impose son utilisation."  },
                { title: "C.R.S", description: "Child Restraint System", details: ""  },
                { title: "C.T.A", description: "Certificat de Transporteur Aérien", details: "Le certificat de transporteur aérien est un agrément attestant la capacité de la compagnie aérienne à réaliser des opérations de transport commercial en toute sécurité. L'agrément est délivré par l'autorité de surveillance du transport aérien."  },
                { title: "D.G.A.C", description: "Direction Générale de l'Aviation Civile", details: "La Direction Générale de l'Aviation Civile engloble une série de principes dont notament : 'sécurité, sûreté, développement durable, régulation économique...'. En d'autres mots, elle s'assure du plus haut niveau de sécutité et de sûreté du transport aérien, aussi bien au sol qu'en vol. Elle a également à coeur de réduire les nuisances (sonores et atmosphériques), l'impact écologique et tout ce qui gravite autour de ces notions."  },
                { title: "A.E.S.A | E.A.S.A", description: "European Aviation Safety Agency | Agence Européenne de la Sécurité Aérienne", details: "Cette agence européenne de la sécurité aérienne joue un rôle davantage législatif en s'assurant de l'homogénéité des réglementations et certifications. Elle élabore les règles techniques de l'aéronautique et certifie certains types d'aéronefs et de composants. Par ailleurs, elle a le droit d'agréer ou non les entreprises chargées de la conception, la fabrication et l'entretien des produits aéronautiques. Elle a également le rôle de surveillance, de soutien et de l'assurance de la sécurité au sein des pays de l'Union Européenne."  },
                { title: "R.I.V | F.I.R", description: "Région Information en Vol | Flight Information Région", details: "Il s'agit d'une portion du ciel bien définie au sein d'un pays. En France, il en existe cinq : 'FIR Paris, Fir Reims, FIR Brest (~40% du traffic total), FIR Bordeaux et enfin FIR Marseille.' Deux services sont exclusifs à chacune de ces régions de vol. En premier lieur celui de navigation aérienne (Contrôle et information en vol). En second lieu, les organismes de recherches et de sauvetage."  },
                { title: "G.T.A", description: "Gendarmerie des Transports Aériens", details: "Il incombe à la Gendarmerie des Transports Aériens de veiller à la sécurité et à la sûreté de l'aviation civile. Elle joue un rôle majeur dans la prévention et la constatation des incidents (sans gravité majeure) ou accidents aériens (gravité majeure). C'est une branche bien spécialisée prête à réagir aux solicitations du directeur général de l'aviation civile. Son action se divise en trois grands pôles : Sûreté et sécurité (lutte contre les interventions illicites), judiciaire (Impliquée dans le relevé des crimes et délits, mène des enquêtes si le pays est impliqué). Enfin elle dispose d'un rôle de renseignement."  },
                { title: "U.A.S | G.P.U", description: "Unité d'Alimentation au Sol | Ground Power Unit", details: "De la même manière que l'Unité d'Alimentation Auxiliaire, elle fournit à l'appareil encore au sol une source d'énergie pour opérer ses systèmes. Ces génératrices sont le plus souvent basées sur une source de carburant fossile comme le diesel. Cependant, ce n'est pas la seule."  },
                { title: "A.T.A.I | I.A.T.A.", description: "Association du Transport Aérien International | International Air Transport Association", details: "L'association du Transport Aérien International regroupe près de 340 compagnies aériennes, représentant 80% du traffic aérien mondial. Son but essentiel est de réprésenter, de mener et de servir l'industrie aéronautique au maximum de ses capacités. Elle est en charge des prises de conscience quant à l'importance des échanges commerciaux à travers le monde et des enjeux capitaux de cette industrie. Elle participe activement à la réduction des coûts des compagnies et fixe les politiques communes de sécurité et d'efficacité au sein de réseau."  },
                { title: "S.D.V | I.F.E", description: "Système de Divertissement en Vol | In-flight Entertainment", details: "C'est une notion qui peut paraître anodine, mais durant des vols dont la durée s'estime parfois à plus d'une dizaine d'heures, en plus de l'émergence des nouvelles technologies, le monde de l'aéronautique a cherché à s'adapter. Pourtant, c'est en 1960 que l'une des plus ferventes tentatives à vu le jour. David Flexer, professionnel du cinéma, a déployé tout son temps, son expertise et son argent pour mettre au point un système de projection assez léger, compacte, automatique et conforme aux normes de l'Admnistration Fédérale de l'Aviation. De nos jours, un simple téléphone permet de contourner les écrans à bords, de surfer sur internet ou encore de regarder des films et vidéos."  },
                { title: "L.M.E | M.L.E", description: "Liste Minimale d'Equipements | Minimal Equipment List", details: "Il s'agit d'une fiche technique où figurent des composants essentiels à un vol en toute sécurité, et leur état. Elle est unique et doit être émise pour chaque vol, informant ainsi chaque nouvelle équipe des potentiels problèmes / incidents rencontrés. Il est à noter que certains appareils sont moins importants que d'autres. Aussi, bien qu'ils doivent impérativement être remis en état dans les délais les plus brefs, ils ne révoquent pas systématiquement la viabilité de l'appareil. Si toutefois une anomalie apparaît capitale, la mention 'NO GO' doit être notée, et l'appareil est alors dans l'obligation de rester au sol."  },
                { title: "C.O.M.S.P | M.O.P.S.C", description: "Configuration opérationnelle maximale des sièges passagers | Maximum Operational Passenger Seating Configuration", details: "Le nombre de sièges disponibles est différent d'un appareil à un autre. Ceci étant, on ne se focalise ici que sur les sièges disponibles à l'usage des passagers, et des passagers uniquement. Ainsi, ce chiffre est plus bas que celui des places totales au sein de l'appareil (pilotes, personnel...)"  },
                { title: "O.2", description: "Oxygène", details: "O² est l'abbrévation chimique pour la composition de l'oxygène. C'est un gaz essentiel à la survie d'un être humain. Cette évidence reste cruciale dans le domaine aéronautique car en altitude, il se raréfie. Certes, à l'intérieur d'un appareil, l'air ambiant est maintenu artificiellement à un niveau proche de celui du sol. Mais en cas d'avarie, de panne, d'erreur technique, tout changement peut induire des confusions, des vertiges, ou mener à la mort."  },
                { title: "O.A.C.I", description: "Organisation de l'Aviation Civile Internationale", details: "Cette organisation prend racine entre novembre et décembre 1944. Elle se divise en trois entités : 'une assemblée, un conseil et un secrétariat'. La première entité est composée de tous les représentants des Etats membres. Elle se réunit tous les trois ans pour fixer un cap quant aux politiques à venir et au budget à alouer. Son rôle est davantage législatif. La seconde est constituée des 36 Etats élus par la première, pour une durée de 3 ans. Certains critères pris en compte dans le vote comme l'importance en matière de transports aériens, la contribution quant aux installations et services où encore la représentation de toutes les principales régions démographiques du monde. En vertu de son rôle davantage exécutif, elle a à sa charge l'adoption des normes et pratiques homogènes consignés dans 'les Annexes à la Convention' relative à l'aviation civile internationale. Enfin, la dernière entité est le secrétariat. Celui-ci est dirigé par le secrétaire général et se divise en cinq directions : 'Navigation aérienne, Transport aérien, Coopération technique, Affaires juridiques et Administration et Services'."  },
                { title: "P.A.F", description: "Police Aux Frontières", details: "Comme son nom l'indique, il s'agit d'une section spécifique de la police chargée de la lutte contre la fraude aux faux documents et à l'identité, de l'immigration irrégulière, ainsi que de la gestion opérationnelle des centre de rétention."  },
                { title: "P.A.X", description: "Passager | Passenger", details: "Abbréviation pour 'Passager'"  },
                { title: "P.E.Q", description: "Personnel d'Equipage", details: "Abbréviation pour 'Personnel d'équipage'"  },
                { title: "P.C.B", description: "Personnel Complémentaire de Bord", details: "Une personne de complémentaire de bord, à la différence du personnel navigant commercial, n'a pas de formation spécifique relative à la sécurité de l'avion dans lequel elle opère. Son rôle est majoritairement orienté vers la satisfaction client et les transactions."  },
                { title: "P.N.C", description: "Personnel Navigant Commercial", details: "Un membre du PNC assure la sécurité à l'intérieur de son appareil, en plus de sa mission d'accueil, de confort et de fidélisation de sa clientèle."  },
                { title: "P.S", description: "Personnel au Sol", details: ""  },
                { title: "U.S.P | P.S.U", description: "Unité de Service aux Passagers | Passenger Service Unit", details: "Il s'agit du composant disposé au-dessus de chaque rangée de sièges, au niveau supérieur de la tête du passager. Ainsi, celui-ci a accès à des hauts-parleurs pour les annonces, des lumières de lecture, des informations comme l'interdiction de cigarette ou même des boutons pour signaler une urgence. Il contient aussi des ventilateurs pour la climatisation et le dispositif d'éjection automatique des masques à oxygène."  },
                { title: "R.E.T.E.X OU R.E.X", description: "Retour d'expérience", details: "Motivées par un perpétuel souci d'excellence et de sécurité, les entreprises ont mis en place des dispositifs pour faire en sorte de ne pas répéter une situation catastrophique, ou d'encourager des comportements prévenant de telles situations. Ainsi, par cette démarche d'apprentissage et d'amélioration continue, on vise à comprendre les causes d'un problème et comment mener efficacement à sa solution."  },
                { title: "R.I.V", description: "Région d'Information de Vol | Flight Information Region", details: "Parties de l'espace aérien dans lesquelles sont fournies diverses informations de vol, au besoin du pilote, et le service d'alerte. Il existe cinq FIR en France : 'Paris, Brest, Bordeaux, Reims et Marseille'. Ainsi, il faut se figurer une carte mentale séparée en cinq tronçons distincts de surveillance, chacun géré par un Centre d'Information en Vol."  },
                { title: "R.E.C | S.A.R", description: "Recherche et Sauvetage | Search and Rescue", details: "Lorsqu'un incident survient, on met en place un opération de Recherche et Sauvetage. En général, il s'agit de cinq phases de développement : 'Conscience, Action Initiale, Planification, Opérations et enfin Conclusion'. La phase de Conscience consiste à réunir toutes les informations utiles, pour dresser une image de la situation. La phase d'Action Initiale permet de soliciter les services compétents quant à la résolution de l'incident, ainsi que d'estimer les ressources nécessaires. La Planification marque l'entrée dans la phase active de l'assistance. On sait comment, on sait pourquoi, et on se prépare à activement répondre à l'incident pour arriver à sa résolution. La phase d'Opération est la concrétisation du plan mis en place, avec le suivi rigoureux de chacune de ses phases, et consigne le déroulement de l'intervention. Enfin, vient le temps de la conclusion. Cette phase marque la fin de l'opération. Elle se caractérise soit par la suspension de l'opération en cas de complications / d'échec ou la mort constatée du ou des personnes impliquées. Mais pour les situations plus heureuses, elle peut aussi se conclure par une réussite de l'opération."  },
                { title: "O.P.S | S.O.P ", description: "Procédures Standards de travail en équipage de l'exploitant | Standard Operating Procedure", details: "Mis en place par la compagnie aérienne, il s'agit d'une base dont le but est d'assister le pilote dans sa mission de pilotage et de sécurité de son appareil. Il regroupe une série d'étapes à suivre rigoureusement pour mener à bien un tâche, ou régler un incident. " },
                { title: "G.T.A.", description: "Gendarmerie des Transports Aériens", details: ""  },
                { title: "T.U.C | U.T.C", description: "Temps Universel Coordonné | Universal Time Coordinated", details: ""  },
            ],
        };
    },
};
  </script>
  